import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './index.css'
import App from './App.jsx'
// PWA service worker registration (generated by vite-plugin-pwa at build time)
import { registerSW } from 'virtual:pwa-register'

// Register the service worker with auto-update
// When a new SW is available it silently updates in the background
const updateSW = registerSW({
  onNeedRefresh() {
    // A new version is available — you could show a toast here if desired
    // For now, auto-accept the update silently
    updateSW(true)
  },
  onOfflineReady() {
    // App is ready to work offline
    console.info('[NexaTech PWA] Ready to work offline.')
  },
  onRegistered(registration) {
    console.info('[NexaTech PWA] Service Worker registered:', registration)
  },
  onRegisterError(error) {
    console.error('[NexaTech PWA] Service Worker registration error:', error)
  },
})

createRoot(document.getElementById('root')).render(
  <StrictMode>
    <App />
  </StrictMode>,
)
